version: '3'

services:
  db:
    image: mysql:5.7
    network_mode: bridge
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: tisaude
      MYSQL_DATABASE: api_ti_saude
      MYSQL_USER: thiago
      MYSQL_PASSWORD: tisaude123
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    network_mode: bridge
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
  webapps:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: bridge
    container_name: webapps
    links:
      - db
    ports:
      - "8080:80"
    restart: always
    env_file:
      - .env
    command: sh -c "while ! nc -z db 3306; do sleep 1; done; php artisan migrate"
volumes:
  dbdata:
